scriptencoding utf-8
" filetype settings
filetype on
filetype plugin on

syntax on
set background=dark

set noswapfile
set hlsearch
set ignorecase
set incsearch
set nowrap

set number
set whichwrap=b,s,h,l,<,>,[,]
set backspace=indent,eol,start
set virtualedit=onemore

set encoding=utf-8
set fileencodings=iso-2022-jp,euc-jp,sjis,utf-8
set fileformats=unix,dos,mac

set hidden
set mouse=a

set laststatus=2

set smartindent
set shiftwidth=4
set scrolloff=3

set tabstop=4
set softtabstop=0
set shiftwidth=4
set expandtab

set clipboard=unnamed

set path+=**
set wildmenu
set showtabline=1

let g:netrw_liststyle=3
let g:netrw_banner=0
let g:netrw_sizestyle="H"
" let g:netrw_timefmt="%Y/%m/%d(%a) %H:%M:%S"
" let g:netrw_preview=1

set guicursor=a:blinkon0
set scrolloff=3

let g:enable_bold_font = 1
let g:enable_italic_font = 1

set list
set listchars=tab:¦\ 
set fillchars=vert:\ 
hi EndOfBuffer guifg=bg
hi VertSplit guibg=#222222

"*****************************************************************************
"" Key-Mappings
"*****************************************************************************
let g:mapleader = "\<Space>"

" general
ino <silent> <C-s>   <ESC>:w<CR>a
nno <silent> <C-s>   :<C-u>w<CR>
nno <silent> q       :<C-u>CloseBufferTab<CR>
nno <silent> <S-q>   :<C-u>qall<CR>
" ino <silent> <C-w>   <ESC><C-w>
" nno          /       /\v
tno <silent> <C-[>   <C-\><C-n>
tno <silent> <ESC>   <C-\><C-n>

" for edit
vno <silent> >       >gv
vno <silent> <       <gv
nno <expr>   <C-d>   ReplaceWordText()  !=# '' ? ':<C-u>'. ReplaceWordText().'<Left><Left><Left>' : '<ESC>'
vno <expr>   <C-d>   VReplaceWordText() !=# '' ? ':<C-u>'.VReplaceWordText().'<Left><Left><Left>' : '<ESC>'

" tab/window
nno <silent> <Right> :<C-u>ChangeBuffer next<CR>
nno <silent> <Left>  :<C-u>ChangeBuffer previous<CR>
nno <silent> +       :<C-u>ResizeWindow +1<CR>
nno <silent> -       :<C-u>ResizeWindow -1<CR>
nno <silent> <Up>    :<C-u>ResizeWindow +1<CR>
nno <silent> <Down>  :<C-u>ResizeWindow -1<CR>

" for yank/delete/paste
nno <silent> c       "_c
vno <silent> c       "_c
nno <silent> C       "_C
vno <silent> C       "_C
nno <silent> s       "_s
vno <silent> s       "_s
nno <silent> S       "_S
vno <silent> S       "_S
nno <silent> x       "_x
vno <silent> x       "_x
vno <silent> p       "_dP
nno <silent> D       "_D
nno <silent> de      "_de
nno <silent> dw      b"_de

" for cursor move
nno <silent> j       gj
nno <silent> k       gk
ino <silent> <C-h>   <Left>
ino <silent> <C-l>   <Right>
nno <silent> <S-h>   10h
nno <silent> <S-j>   5gj
nno <silent> <S-k>   5gk
nno <silent> <S-l>   10l
vno <silent> <S-h>   10h
vno <silent> <S-j>   5gj
vno <silent> <S-k>   5gk
vno <silent> <S-l>   10l
ino <silent> <M-h> <Left>
ino <silent> <M-j> <Down>
ino <silent> <M-k> <Up>
ino <silent> <M-l> <Right>
tno <silent> <M-h> <Left>
tno <silent> <M-j> <Down>
tno <silent> <M-k> <Up>
tno <silent> <M-l> <Right>
nno <silent> <M-u> <PageUp>
nno <silent> <M-d> <PageDown>
cno          <C-a> <Home>
cno          <C-e> <End>

" for IME
nno <silent> あ      a
nno <silent> い      i
nno <silent> う      u
nno <silent> お      o
nno <silent> ｒ      r
nno <silent> ｊ      gj
nno <silent> ｋ      gj
nno <silent> ｌ      l
nno <silent> ｈ      h
nno <silent> ｐ      p
nno <silent> ｄｄ    dd
nno <silent> ｙｙ    yy

"" Mapping for Plugins
nno <silent> <C-f> :<C-u>call VimGrepWord()<CR>
vno <silent> <C-f> :<C-u>call VVimGrepWord()<CR>

"" mapping for My Commands
ino <silent> <A-;>    <ESC>:<C-u>Appendchar ;<CR>a
no  <silent> <A-;>         :<C-u>Appendchar ;<CR>
nno <silent> <leader>l  :<C-u>SetHlSearch<CR>
nno <silent> t          :<C-u>bo terminal ++rows=12<CR>
nno <silent> <C-n>      :<C-u>Explore<CR>


"*****************************************************************************
"" Functions
"*****************************************************************************

fun! s:changebuffer(direction) abort
    " バッファタブを切り替える関数
    " directionにはnextかpreviousを指定する
    if tabpagenr('$') == 1
        if &buflisted
            if a:direction ==? 'next' || a:direction ==? 'n'
                let l:cmd = 'bnext'
            elseif a:direction ==? 'previous' || a:direction ==? 'p'
                let l:cmd = 'bprevious'
            else
                return
            endif
            exe l:cmd
            let l:termflag = str2nr(buffer_name('%')[0])
            if l:termflag
                setlocal nonumber
            else
                setlocal number
            endif
        endif
    else
        if a:direction ==? 'next' || a:direction ==? 'n'
            let l:cmd = 'tabnext'
        elseif a:direction ==? 'previous' || a:direction ==? 'p'
            let l:cmd = 'tabprevious'
        else
            return
        endif
        exe l:cmd
    endif
endf
command! -nargs=1 ChangeBuffer call s:changebuffer(<f-args>)


fun! s:closebuffertab() abort
    " バッファタブを閉じる関数
    " バッファリストの数をカウント
    let l:buf_number = 0
    for l:i in range(1, bufnr('$'))
        if buflisted(l:i)
            let l:buf_number += 1
        endif
    endfor
    if tabpagenr('$') > 1
        if l:buf_number == 1
            tabclose
        else
            if &buflisted
                exe 'bd '.buffer_number('%')
            else
                quit
            endif
        endif
    else
        try
            if winnr('$') == 1
                " 単一ウィンドウの場合
                if l:buf_number == 1
                    " バッファリストが１つの場合 quit
                    quit
                    return
                else
                    call s:deletebuffer()
                    return
                endif
            elseif winnr('$') > 1
                " 複数ウィンドウの場合
                if len(win_findbuf(bufnr('%'))) == 1 && &buflisted
                    " 異なるファイルを画面分割している場合
                    if l:buf_number == 1 || &buftype ==? 'quickfix'
                        " バッファリストが１つ、または特定のバッファタイプの場合quit
                        quit
                        return
                    else
                        call s:deletebuffer()
                        if l:buf_number == 2
                            quit
                        endif
                        return
                    endif
                else
                    " 同じファイルを画面分割している、またはバッファリストにないウィンドウの場合
                    quit
                    return
                endif
            endif
        catch
            echoerr 'CloseBufferTab: [error] "'.bufname('%').'" を閉じることができません。'
            return
        endtry
    endif
endf
command! CloseBufferTab call s:closebuffertab()


fun! s:deletebuffer() abort
    " buffer deleteのwrapper関数
    try
        let l:deletebufnr = bufnr('%')
        let l:beforebufnr = bufnr('#')
        " 1つ前に編集していたバッファがあれば戻る、なければbnext
        if l:beforebufnr != -1 && buflisted(l:beforebufnr)
            exe 'buffer '.l:beforebufnr
        else
            bnext
        endif
        exe 'bdelete! '.l:deletebufnr
    catch
    endtry
endf


fun! s:CloseNetrw() abort
  for bufn in range(1, bufnr('$'))
    if bufexists(bufn) && getbufvar(bufn, '&filetype') ==# 'netrw'
      silent! execute 'bwipeout ' . bufn
      if getline(2) =~# '^" Netrw '
        silent! bwipeout
      endif
      return
    endif
  endfor
endf
autocmd FileType netrw nnoremap <buffer><silent> <Esc> :call <SID>CloseNetrw()<CR>
autocmd FileType netrw nnoremap <buffer><silent> q     :call <SID>CloseNetrw()<CR>
autocmd FileType netrw nnoremap <buffer><silent> <C-n> :call <SID>CloseNetrw()<CR>


fun! s:resizewindow(size) abort
    " 分割ウィンドウの高さと幅を調節する関数
    "      :ResizeWindow + でカレントウィンドウを広くする
    "      :ResizeWindow - でカレントウィンドウを狭くする
    "      以下のマッピングがおすすめ
    "      nno +  :ResizeWindow +<CR>
    "      nno -  :ResizeWindow -<CR>
    if a:size ==# ''
        echon '[warning] the args "size" is empty.'
        return
    endif
    if winwidth(0) >= winheight(0)*3
        exe 'res '.a:size
    else
        exe 'vertical res '.a:size
    endif
endf
command! -nargs=1 ResizeWindow call s:resizewindow(<f-args>)


fun! s:make(...) abort
    " makeコマンドを走らせる関数
    let l:current_dir = expand('%:p:h')
    let l:command = 'make '.join(a:000)
    if findfile('GNUmakefile',l:current_dir) !=# ''
       \|| findfile('Makefile',l:current_dir) !=# ''
        call term_start(l:command)
    elseif findfile('GNUmakefile',l:current_dir.'/../') !=# ''
           \|| findfile('Makefile',l:current_dir.'/../') !=# ''
        let l:command = 'cd ../ && '.l:command
        call term_start(l:command)
    else
        echon 'not found: "GNUmakefile" or "Makefile"'
    endif
endf
command! -nargs=* Make call s:make(<f-args>)


fun! s:getprojectname(cmakelists_txt) abort
    " CMakeLists.txtからプロジェクト名を取得する関数
    "      CMake関数で利用している
    if findfile(a:cmakelists_txt,getcwd()) !=# ''
        let  l:cmakelists_txt = a:cmakelists_txt
    elseif findfile(a:cmakelists_txt,getcwd().'/../') !=# ''
        let  l:cmakelists_txt = '../'.a:cmakelists_txt
    else
        return
    endif
    for l:line in readfile(l:cmakelists_txt)
        let l:AddExe = matchstrpos(l:line,'add_executable')
        if l:AddExe[0] !=# ''
            let l:Name = split(l:line[l:AddExe[2]+1:],' ')[0]
            return l:Name
        endif
    endfor
endf


fun! s:appendchar(...) abort range
    " カーソルがある行の末尾に引数の文字を追加する関数
    "      C言語,js等で末尾にセミコロンをつけるときに使う
    "      すでに指定の文字が末尾にあれば追加しない。
    "      :AppendChar ;
    let l:pos = getpos('.')
    let l:pos[1] = a:lastline
    let l:args = join(a:000)
    let l:len = len(l:args)
    if !l:len
        return
    endif
    for l:linenum in range(a:firstline,a:lastline)
        call setpos('.', [0,l:linenum,0,0])
        let l:line = getline('.')
        if l:line[len(l:line)-l:len :] ==# l:args
            continue
        endif
        exe 'silent normal A'.l:args
    endfor
    call setpos('.', l:pos)
endf
command! -nargs=* -range Appendchar :<line1>,<line2>call s:appendchar(<f-args>)


fun! s:sethlsearch() abort
    " 検索結果のハイライトのオン/オフ切り替え
    if &hlsearch
        set nohlsearch
    else
        set hlsearch
    endif
endf
command! SetHlSearch call s:sethlsearch()


fun! ReplaceWord(...) abort
    let l:target = expand('<cword>')
    if a:0 > 0
        let l:text = join(a:000)
    else
        echoerr 'no argument.'
        return
    endif
    exe line('.').',$s/'.l:target.'/'.l:text.'/gc'
endf
command! -nargs=* ReplaceWord call ReplaceWord(<f-args>)


fun! VReplaceWord(...) abort range
    if a:0 > 0
        let l:text = join(a:000)
    else
        echoerr 'no argument.'
        return
    endif
    let @@ = ''
    exe 'silent normal gvy'
    if @@ !=# ''
        let l:target = join(split(@@,'\n'))
        exe line('.').',$s/'.l:target.'/'.l:text.'/gc'
    endif
endf
command! -range -nargs=* VReplaceWord call VReplaceWord(<f-args>)


fun! ReplaceWordText() abort
    let l:target = expand('<cword>')
    if l:target !=# ''
        return line('.').',$s/'.l:target.'//gc'
    else
        return ''
    endif
endf


fun! VReplaceWordText() abort range
    let l:target = s:get_vselect_txt()
    if l:target !=# ''
        return line('.').',$s/'.l:target.'//gc'
    else
        return ''
    endif
endf


fun! s:get_vselect_txt()
    if mode()=="v"
        let [line_start, column_start] = getpos("v")[1:2]
        let [line_end, column_end] = getpos(".")[1:2]
    else
        let [line_start, column_start] = getpos("'<")[1:2]
        let [line_end, column_end] = getpos("'>")[1:2]
    end
    if (line2byte(line_start)+column_start) > (line2byte(line_end)+column_end)
        let [line_start, column_start, line_end, column_end] =
        \   [line_end, column_end, line_start, column_start]
    end
    let lines = getline(line_start, line_end)
    if len(lines) == 0
            return ''
    endif
    let lines[-1] = lines[-1][: column_end - 1]
    let lines[0] = lines[0][column_start - 1:]
    return join(lines, "\n")
endf


fun! s:jqfmt() abort
    if executable("jq")
        let l:pos = getpos('.')
        silent exe "0, $!jq -r ."
        call setpos('.', l:pos)
    else
        echoerr "jq not found."
    endif
endf
command! Jq call s:jqfmt()


fun! VimGrepWord(...) abort
    call system('git status')
    if v:shell_error ==# 0
        let l:target = '`git ls-files`'
    else
        let l:target = '**'
    endif
    if a:0 == 0
        let l:pattern = expand('<cword>')
    else
        let l:pattern = join(a:000)
    endif
    silent exe 'vimgrep /'.l:pattern.'/ '.l:target.' | cw'
endf
command! -nargs=* VimGrepWord call VimGrepWord(<f-args>)


fun! VVimGrepWord() abort range
    call system('git status')
    if v:shell_error ==# 0
        let l:target = '`git ls-files`'
    else
        let l:target = '**'
    endif
    let @@ = ''
    exe 'silent normal gvy'
    if @@ !=# ''
        let l:pattern = join(split(@@,'\n'))
        silent exe 'vimgrep /'.l:pattern.'/ '.l:target.' | cw'
    endif
endf


fun! GetNow() abort
    " 現在時刻を取得する関数
    let l:day = printf('%d', strftime('%d'))
    let l:nday = l:day[len(l:day)-1]
    let l:daytail = 'th'
    if     l:nday == 1
        let l:daytail = 'st'
    elseif l:nday == 2
        let l:daytail = 'nd'
    elseif l:nday == 3
        let l:daytail = 'rd'
    endif
    let l:day = l:day . l:daytail . ' '
    let l:nweek = strftime('%w')
    let l:weeks = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
    let l:week = l:weeks[l:nweek] . ' '
    let l:nmonth = strftime('%m') - 1
    let l:months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    let l:month = l:months[l:nmonth] . ' '
    let l:now = l:week . l:month . l:day
    let l:now .= strftime('%H:%M:%S %Y')
    " let l:now .= strftime('%H:%M:%S %z (%Z) %Y')
    " let l:now = strftime('%Y-%m-%d(%a) %H:%M:%S')
    return l:now
endf


fun! s:git(...) abort
    " gitコマンドを実行する関数
    if a:1 ==# 'acp'
        if a:0 >= 2
            let l:cmd = 'git add -A && git commit -m "'.join(a:000[1:], ' ').'" && git push -u'
        else
            let l:cmd = 'git add -A && git commit -m "`date`" && git push -u'
        endif
        call s:git_autocmd()
    elseif a:1 ==# 'pull'
        let l:cmd = 'git pull'
        call s:git_autocmd()
    elseif a:1 ==# 'fpull'
        let l:cmd = 'git reset --hard && git pull'
        call s:git_autocmd()
    elseif a:1 ==# 'diff'
        let l:cmd = 'git status -v -v'
    elseif a:1 ==# 'reset'
        let l:cmd = 'git reset --hard'
        call s:git_autocmd()
    elseif a:1 ==# 'blame'
        let l:cmd = 'git blame '.expand('%:p')
    else
        let l:cmd = 'git '.join(a:000)
    endif
    let l:script_winid = win_getid()
    let s:git_wininfo = term_start(l:cmd)
    call win_gotoid(l:script_winid)
endf
fun! s:CompletionGitCommands(ArgLead, CmdLine, CusorPos)
    return filter(['acp', 'pull', 'fpull',  'diff', 'reset', 'status', 'blame', 'show'], printf('v:val =~ "^%s"', a:ArgLead))
endf
command! -complete=customlist,s:CompletionGitCommands -nargs=* Git call s:git(<f-args>)

fun! s:git_autocmd() abort
    aug git_auto_command
        au CursorHold <buffer> call s:git_close()
    aug END
endf

fun! s:git_close() abort
    let l:script_winid = win_getid()
    if splitterm#exist(s:git_wininfo)
        \&& win_gotoid(s:git_wininfo.console_winid)
        let l:lines = getline(0, '$')
        for l:line in l:lines
            if l:line ==# '[Process exited 0]'
                quit
                edit
            endif
        endfor
        call win_gotoid(l:script_winid)
    else
        aug git_auto_command
            au!
        aug END
    endif
endf

