[terminal]
shell = { program = "wsl.exe", args = [ "--cd ~", "--exec /usr/bin/zsh -l" ] }

[font]
normal = { family = "HackGen Console NF", style = "Regular" }
bold = { family = "HackGen Console NF", style = "Bold" }
size = 13
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 1 }

[env]
TERM = "screen-256color"

[window]
dimensions = { columns = 130, lines = 45 }
position = { x = 0, y = 0 }
startup_mode = "Windowed"
title = "Ubuntu"
dynamic_title = false
decorations = "full"
opacity = 0.98
# blur = true  # does not work on Windows

[scrolling]
history = 50000

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
{ key = "V",     mods = "Control|Shift", action = "Paste" },
{ key = "C",     mods = "Control|Shift", action = "Copy" },
{ key = "Plus",  mods = "Control",       action = "IncreaseFontSize" },
{ key = "Minus", mods = "Control",       action = "DecreaseFontSize" },
]

[colors]
primary = { background = "0x1a1b26", foreground = "0xd0dae5" }
normal = { black = "0x15161E", red = "0xf7768e", green = "0x9ece6a",  yellow = "0xe0af68",  blue = "0x7aa2f7",  magenta = "0xbb9af7",  cyan = "0x7dcfff",  white = "0xc9d1e6" }
bright = { black = "0x616888", red = "0xf7768e",  green = "0x9ece6a",  yellow = "0xe0af68",  blue = "0x7aa2f7",  magenta = "0xbb9af7",  cyan = "0x7dcfff",  white = "0xd0dae5" }
indexed_colors = [
{ index = 16, color = "0xff9e64" },
{ index = 17, color = "0xdb4b4b" }
]
