scriptencoding utf-8
" filetype settings
filetype on
filetype plugin on

syntax on
if has('mac')
    set termguicolors " for iTerm2
endif
set background=dark

set noswapfile
set hlsearch
set ignorecase
set incsearch
set nowrap

set number
set whichwrap=b,s,h,l,<,>,[,]
set backspace=indent,eol,start
set virtualedit=onemore

set encoding=utf-8
set fileencodings=iso-2022-jp,euc-jp,sjis,utf-8
set fileformats=unix,dos,mac

set hidden
set mouse=a

set laststatus=2

set smartindent
set shiftwidth=4
set scrolloff=3

set tabstop=4
set softtabstop=0
set shiftwidth=4
set expandtab

set clipboard=unnamed

set path+=**
set wildmenu
set showtabline=1

set guicursor=a:blinkon0
set scrolloff=3

let g:enable_bold_font = 1
let g:enable_italic_font = 1

set list
set listchars=tab:¦\ 
set fillchars=vert:\ 
hi EndOfBuffer guifg=bg
hi VertSplit guibg=#222222

" setting of python for neovim
let g:python2_host_prog = '~/.pyenv/shims/python'
let g:python3_host_prog = '~/.pyenv/shims/python3'

" runtime of user vim settings (~/.vim/vimrc/*.vim)
ru! vimrc/*.vim

