# ----------------------------
# `sheldon` configuration file
# ----------------------------

shell = "zsh"
apply = []

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[templates]
defer = "{% for file in files %}source \"{{ file }}\"\n{% endfor %}"

[plugins.compinit]
inline = "autoload -Uz compinit && compinit"

[plugins.bashcompinit]
inline = "autoload -Uz bashcompinit && bashcompinit"

[plugins.tetriscurses]
inline = "autoload -Uz tetriscurses"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-256color]
github = "chrissicool/zsh-256color"
apply = ["defer"]

[plugins.zsh-better-npm-completion]
github = "lukechilds/zsh-better-npm-completion"
apply = ["defer"]

