# `sheldon` configuration file
# ----------------------------

shell = "zsh"
apply = ["defer"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
# defer = ""

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.bashcompinit]
inline = 'autoload -Uz bashcompinit && zsh-defer bashcompinit'

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-256color]
github = "chrissicool/zsh-256color"
apply = ["defer"]

