# ----------------------------
# `sheldon` configuration file
# ----------------------------

shell = "zsh"
apply = []

[plugins.compinit]
inline = "autoload -Uz compinit && compinit"

[plugins.bashcompinit]
inline = "autoload -Uz bashcompinit && bashcompinit"

[plugins.tetriscurses]
inline = "autoload -Uz tetriscurses"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-256color]
github = "chrissicool/zsh-256color"

[plugins.zsh-better-npm-completion]
github = "lukechilds/zsh-better-npm-completion"

