# place this file to %AppData%\neovide\config.toml
fork = false
frame = "full"
idle = true
maximized = false
mouse-cursor-icon = "arrow"
neovim-bin = "$HOME/Project/nvim/squashfs-root/usr/bin/nvim"
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = true

[font]
normal = ["HackGen Console NF"]
size = 12.0

